//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fast_Food_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_1
    {
        public admin_1()
        {
            this.admin_staff = new HashSet<admin_staff>();
            this.User_RegLogin = new HashSet<User_RegLogin>();
        }
    
        public int admin_id { get; set; }
        public string AdminName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public System.DateTime date_time { get; set; }
    
        public virtual ICollection<admin_staff> admin_staff { get; set; }
        public virtual ICollection<User_RegLogin> User_RegLogin { get; set; }
    }
}
