//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fast_Food_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_staff
    {
        public int admin_staff_id { get; set; }
        public Nullable<int> Staff_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public System.DateTime date_time { get; set; }
    
        public virtual admin_1 admin_1 { get; set; }
        public virtual staff staff { get; set; }
    }
}
