//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fast_Food_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int FeedBack_id { get; set; }
        public string Fisrt_Name { get; set; }
        public string Last_Name { get; set; }
        public string City { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date_Time { get; set; }
    }
}
