//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fast_Food_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public tbl_product()
        {
            this.tbl_order = new HashSet<tbl_order>();
        }
    
        public int pro_Food_id { get; set; }
        public string pro_FoodName { get; set; }
        public string pro_FoodDescription { get; set; }
        public long pro_FoodPrice { get; set; }
        public string pro_dealsName { get; set; }
        public string pro_FoodImage { get; set; }
        public Nullable<System.DateTime> pro_Date_Time { get; set; }
    
        public virtual ICollection<tbl_order> tbl_order { get; set; }
    }
}
