//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fast_Food_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Login
    {
        public User_Login()
        {
            this.tbl_invoice = new HashSet<tbl_invoice>();
            this.User_RegLogin = new HashSet<User_RegLogin>();
        }
    
        public int Login_id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime date_time { get; set; }
    
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
        public virtual ICollection<User_RegLogin> User_RegLogin { get; set; }
    }
}
