//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fast_Food_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Registration
    {
        public User_Registration()
        {
            this.User_RegLogin = new HashSet<User_RegLogin>();
        }
    
        public int Reg_id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Reg_Type { get; set; }
        public string Gender { get; set; }
        public System.DateTime date_time { get; set; }
    
        public virtual ICollection<User_RegLogin> User_RegLogin { get; set; }
    }
}
