//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fast_Food_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_RegLogin
    {
        public int RegLogin_id { get; set; }
        public Nullable<int> Login_id { get; set; }
        public Nullable<int> Registraion_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public System.DateTime date_time { get; set; }
    
        public virtual admin_1 admin_1 { get; set; }
        public virtual User_Login User_Login { get; set; }
        public virtual User_Registration User_Registration { get; set; }
    }
}
